#include "measurement/measurement_controller.hpp"
#include "motor/stepper_motor.hpp"
#include "config/config_storage.hpp"
#include "esp_log.h"
#include "esp_timer.h"
#include <cmath>
#include <cstring>
static const char *TAG="measurement"; static uint32_t now_ms(){return static_cast<uint32_t>(esp_timer_get_time()/1000);}
const char *state_name(DeviceState s){switch(s){case DeviceState::IDLE:return"IDLE";case DeviceState::MANUAL_LEFT:return"MANUAL_LEFT";case DeviceState::MEASURING:return"MEASURING";case DeviceState::CALIBRATING:return"CALIBRATING";case DeviceState::FINISHED:return"FINISHED";case DeviceState::STOPPED:return"STOPPED";case DeviceState::ERROR:return"ERROR";}return"ERROR";}
const char *error_name(ErrorCode e){switch(e){case ErrorCode::None:return"NONE";case ErrorCode::NeedleNotFound:return"NEEDLE_NOT_FOUND";case ErrorCode::ContactAlreadyActive:return"CONTACT_ALREADY_ACTIVE";case ErrorCode::MeasurementTimeout:return"MEASUREMENT_TIMEOUT";case ErrorCode::CalibrationTimeout:return"CALIBRATION_TIMEOUT";case ErrorCode::MaxStepsReached:return"MAX_STEPS_REACHED";case ErrorCode::NotCalibrated:return"NOT_CALIBRATED";case ErrorCode::StopActive:return"STOP_ACTIVE";case ErrorCode::InvalidConfig:return"INVALID_CONFIG";case ErrorCode::InternalError:return"INTERNAL_ERROR";}return"INTERNAL_ERROR";}
esp_err_t MeasurementController::init(StepperMotor*m,GpioManager*g,ConfigStorage*s,DeviceConfig c,DeviceStats st){if(!m||!g||!s){ESP_LOGE(TAG,"Null dependency");return ESP_ERR_INVALID_ARG;}motor_=m;gpio_=g;storage_=s;config_=c;stats_=st;gpio_queue_=xQueueCreate(16,sizeof(GpioEvent));command_queue_=xQueueCreate(8,sizeof(ControllerCommand));mutex_=xSemaphoreCreateMutex();if(!gpio_queue_||!command_queue_||!mutex_){ESP_LOGE(TAG,"FreeRTOS allocation failed: gpio=%p command=%p mutex=%p",gpio_queue_,command_queue_,mutex_);return ESP_ERR_NO_MEM;}return gpio_->init(gpio_queue_,motor_);}
esp_err_t MeasurementController::start_task(){if(!gpio_queue_||!command_queue_||!mutex_||!motor_||!gpio_||!storage_){ESP_LOGE(TAG,"Controller is not initialized");return ESP_ERR_INVALID_STATE;}if(xTaskCreate(task_entry,"measurement",4096,this,10,nullptr)!=pdPASS){ESP_LOGE(TAG,"Cannot create controller task");return ESP_ERR_NO_MEM;}return ESP_OK;} void MeasurementController::task_entry(void*c){static_cast<MeasurementController*>(c)->run();}
bool MeasurementController::enqueue(CommandType c){if(!command_queue_){ESP_LOGE(TAG,"Command queue is null");return false;}ControllerCommand x{c};return xQueueSend(command_queue_,&x,0)==pdTRUE;}
bool MeasurementController::update_config(const DeviceConfig&c,const char**r){if(!validate_config(c,r))return false;if(!mutex_){if(r)*r="Controller is not initialized";return false;}if(xSemaphoreTake(mutex_,pdMS_TO_TICKS(50))!=pdTRUE){if(r)*r="Controller busy";return false;}if(state_!=DeviceState::IDLE){xSemaphoreGive(mutex_);if(r)*r="Settings can be changed only in IDLE";return false;}bool scale_changed=std::fabs(c.calibration_length_mm-config_.calibration_length_mm)>1e-12||std::fabs(c.mm_per_step-config_.mm_per_step)>1e-12||c.measurement_sign!=config_.measurement_sign;config_=c;if(scale_changed){stats_.calibration_valid=false;stats_.measurements_since_calibration=0;}esp_err_t e=storage_->save_config(config_);if(e==ESP_OK&&scale_changed)e=storage_->save_stats(stats_);xSemaphoreGive(mutex_);if(e!=ESP_OK){if(r)*r="NVS write failed";return false;}return true;}
bool MeasurementController::snapshot(StatusSnapshot&o){if(!mutex_||!gpio_||!motor_){ESP_LOGE(TAG,"Snapshot requested before controller initialization");return false;}xSemaphoreTake(mutex_,portMAX_DELAY);o={state_,error_,gpio_->needle_present(),gpio_->contact_active(),gpio_->stop_active(),motor_->is_enabled(),stats_,config_};xSemaphoreGive(mutex_);return true;} double MeasurementController::calculate_length(uint32_t n)const{return config_.calibration_length_mm+config_.measurement_sign*(static_cast<double>(stats_.calibration_steps)-n)*config_.mm_per_step;} bool MeasurementController::debounced(uint32_t n,uint32_t&l)const{if(n-l<config_.debounce_ms)return false;l=n;return true;}
void MeasurementController::run(){if(!gpio_queue_||!command_queue_||!mutex_||!motor_||!gpio_||!storage_){ESP_LOGE(TAG,"Controller task started without required handles");if(motor_)motor_->stop();vTaskDelete(nullptr);return;}ESP_LOGI(TAG,"Controller started");for(;;){GpioEvent g;ControllerCommand c;xSemaphoreTake(mutex_,portMAX_DELAY);while(xQueueReceive(gpio_queue_,&g,0)==pdTRUE)process_gpio(g);while(xQueueReceive(command_queue_,&c,0)==pdTRUE)process_command(c);tick();xSemaphoreGive(mutex_);vTaskDelay(pdMS_TO_TICKS(1));}}
void MeasurementController::process_gpio(const GpioEvent&e){uint32_t n=now_ms();if(e.type==GpioEventType::StopActive&&e.level_low){safe_stop();state_=DeviceState::STOPPED;error_=ErrorCode::StopActive;return;}if(e.type==GpioEventType::ContactActive&&e.level_low&&(state_==DeviceState::MEASURING||state_==DeviceState::CALIBRATING)){finish_contact();return;}if(e.type==GpioEventType::MeasurePressed&&e.level_low&&debounced(n,last_measure_ms_))start_measurement(false);if(e.type==GpioEventType::CalibratePressed&&e.level_low&&debounced(n,last_calibrate_ms_))start_measurement(true);}
void MeasurementController::process_command(const ControllerCommand&c){switch(c.type){case CommandType::Measure:start_measurement(false);break;case CommandType::Calibrate:start_measurement(true);break;case CommandType::ResetStop:if(state_==DeviceState::STOPPED&&!gpio_->stop_active()){motor_->clear_stop_latch();motor_->clear_abort();state_=DeviceState::IDLE;error_=ErrorCode::None;}break;case CommandType::ResetError:if(state_==DeviceState::ERROR){motor_->clear_abort();state_=DeviceState::IDLE;error_=ErrorCode::None;}break;case CommandType::FactoryReset:if(state_==DeviceState::IDLE)storage_->factory_reset(config_,stats_);break;}}
void MeasurementController::start_measurement(bool cal){if(state_!=DeviceState::IDLE&&state_!=DeviceState::FINISHED)return;if(gpio_->stop_active()){safe_stop();state_=DeviceState::STOPPED;error_=ErrorCode::StopActive;return;}if(!cal&&!gpio_->needle_present()){fail(ErrorCode::NeedleNotFound);return;}if(!cal&&!stats_.calibration_valid){fail(ErrorCode::NotCalibrated);return;}if(gpio_->contact_active()){fail(ErrorCode::ContactAlreadyActive);return;}motor_->clear_abort();uint32_t sp=cal?config_.calibration_speed_steps_s:config_.measurement_speed_steps_s,lim=cal?config_.max_calibration_steps:config_.max_measurement_steps;if(motor_->start(config_.measure_dir_inverted,sp,lim,config_.step_high_us)!=ESP_OK){fail(ErrorCode::InternalError);return;}started_ms_=now_ms();state_=cal?DeviceState::CALIBRATING:DeviceState::MEASURING;error_=ErrorCode::None;}
void MeasurementController::finish_contact(){uint32_t s=motor_->completed_steps();bool cal=state_==DeviceState::CALIBRATING;safe_stop();if(cal){stats_.calibration_steps=s;stats_.calibration_valid=true;stats_.measurements_since_calibration=0;++stats_.calibration_count;storage_->save_stats(stats_);state_=DeviceState::FINISHED;return;}stats_.last_measurement_steps=s;stats_.last_measured_length=calculate_length(s);stats_.last_deviation=stats_.last_measured_length-config_.nominal_length_mm;std::strncpy(stats_.last_result,std::fabs(stats_.last_deviation)<=config_.tolerance_mm?"OK":(stats_.last_deviation<0?"TOO_SHORT":"TOO_LONG"),sizeof(stats_.last_result));stats_.last_result[sizeof(stats_.last_result)-1]=0;++stats_.measurements_since_calibration;++stats_.total_measurements;storage_->save_stats(stats_);state_=DeviceState::FINISHED;}
void MeasurementController::safe_stop(){motor_->stop();}void MeasurementController::fail(ErrorCode e){safe_stop();error_=e;state_=DeviceState::ERROR;ESP_LOGW(TAG,"%s",error_name(e));}
void MeasurementController::tick(){uint32_t n=now_ms();if(gpio_->stop_active()&&state_!=DeviceState::STOPPED){motor_->emergency_stop_isr();state_=DeviceState::STOPPED;error_=ErrorCode::StopActive;return;}if((state_==DeviceState::MEASURING||state_==DeviceState::CALIBRATING)){if(gpio_->contact_active()){finish_contact();return;}if(state_==DeviceState::MEASURING&&!gpio_->needle_present()){fail(ErrorCode::NeedleNotFound);return;}if(motor_->limit_reached()){fail(ErrorCode::MaxStepsReached);return;}uint32_t t=state_==DeviceState::MEASURING?config_.measurement_timeout_ms:config_.calibration_timeout_ms;if(n-started_ms_>=t){fail(state_==DeviceState::MEASURING?ErrorCode::MeasurementTimeout:ErrorCode::CalibrationTimeout);return;}}bool left=gpio_->left_pressed();if(state_==DeviceState::IDLE&&left){motor_->clear_abort();if(motor_->start(config_.left_dir_inverted,config_.manual_speed_steps_s,0xffffffff,config_.step_high_us)==ESP_OK)state_=DeviceState::MANUAL_LEFT;}if(state_==DeviceState::MANUAL_LEFT&&(!left||motor_->abort_requested()||(config_.stop_manual_on_contact&&gpio_->contact_active()))){safe_stop();state_=DeviceState::IDLE;}if(state_==DeviceState::FINISHED&&config_.disable_motor_when_idle)state_=DeviceState::IDLE;}
