[platformio]
src_dir = main

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.sdkconfig_defaults = sdkconfig.defaults
