[env:esp32-c3-supermini]
platform = espressif32 @ 6.7.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
board_build.filesystem = littlefs
board_build.arduino.usb_cdc_on_boot = 1
board_build.arduino.usb_mode = 1
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D CORE_DEBUG_LEVEL=3
  -Isrc/config
  -Isrc/motor
  -Isrc/input
  -Isrc/measurement
  -Isrc/network
  -Isrc/web
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
