#pragma once
#include <Arduino.h>

static const char INDEX_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NeedleGauge</title><style>
*{box-sizing:border-box}body{margin:0;background:#101826;color:#e7edf7;font:16px system-ui,sans-serif}.wrap{max-width:980px;margin:auto;padding:18px}h1{margin:0 0 14px}.tabs button,.actions button{background:#25334a;color:#fff;border:0;border-radius:8px;padding:10px 14px;margin:0 6px 12px 0;cursor:pointer}.tabs button.on{background:#1476d4}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.card{background:#192436;border-radius:12px;padding:15px}.value{font-size:1.75rem;font-weight:700}.result{border-left:7px solid #64748b}.green{border-color:#24b36b}.yellow{border-color:#eab308}.red{border-color:#ef4444}.muted{color:#aab7c9}.hidden{display:none}fieldset{border:1px solid #3a4b65;border-radius:10px;margin:12px 0;padding:12px}legend{color:#93c5fd}label{display:block;margin:8px 0}input{float:right;width:48%;background:#0e1624;color:#fff;border:1px solid #52647e;border-radius:5px;padding:5px}.notice{min-height:1.4em;color:#9dd3ff}@media(max-width:500px){input{width:57%}}
</style></head><body><main class="wrap"><h1>Измеритель длины игл</h1><div class="tabs"><button class="on" onclick="tab('dash')">Панель</button><button onclick="tab('settings')">Настройки</button></div>
<section id="dash"><div id="result" class="card result"><div class="muted">Длина</div><div id="length" class="value">—</div><div id="devmm">Отклонение: —</div><div id="devpct">Отклонение: —</div></div><div class="grid" style="margin-top:12px"><div class="card"><div class="muted">Состояние устройства</div><div id="state" class="value" style="font-size:1.2rem">Загрузка…</div><div id="error"></div></div><div class="card" id="facts"></div><div class="card" id="wifi"></div></div></section>
<section id="settings" class="hidden"><form id="form"><div id="fields"></div><div class="actions"><button type="submit">Сохранить</button><button type="button" onclick="loadConfig()">Отменить изменения</button><button type="button" onclick="resetConfig()">Сбросить настройки по умолчанию</button></div><div class="notice" id="notice"></div></form></section></main><script>
const groups={"Механика":['motorStepsPerRev','microsteps','gearboxRatio','screwLeadMm','stepsPerMmOverride','directionInverted','measurementSign'],"Калибровка":['calibrationLengthMm','doubleTouchEnabled','contactBackoffMm'],"Скорости":['manualLeftSpeedMmS','measurementSpeedMmS','fineMeasurementSpeedMmS','calibrationSpeedMmS','fineCalibrationSpeedMmS','accelerationMmSS'],"Автоматика":['automaticModeEnabled','autoMeasurementDelayMs','needleDetectDebounceMs','needleRemovedDebounceMs'],"Допуски":['deviationGreenPercent','deviationRedPercent'],"Безопасность":['buttonDebounceMs','contactDebounceMs','maxMeasurementTravelMm','maxCalibrationTravelMm','maxMeasurementTimeMs','maxCalibrationTimeMs','maxContinuousManualLeftTimeMs'],"Wi-Fi":['wifiSsid','wifiPassword','wifiConnectTimeoutMs','wifiRetryIntervalMs','fallbackApSsid','fallbackApPassword']};
const names={motorStepsPerRev:'Шагов двигателя/об',microsteps:'Микрошаг',gearboxRatio:'Передаточное число',screwLeadMm:'Ход ШВП (мм/об)',stepsPerMmOverride:'Переопределение steps/mm (0 = расчёт)',directionInverted:'Инвертировать направление',measurementSign:'Знак измерения (1 / -1)',calibrationLengthMm:'Длина калибра (мм)',doubleTouchEnabled:'Двухэтапное касание',contactBackoffMm:'Отъезд после касания (мм)',manualLeftSpeedMmS:'Ручной отъезд (мм/с)',measurementSpeedMmS:'Измерение (мм/с)',fineMeasurementSpeedMmS:'Точное измерение (мм/с)',calibrationSpeedMmS:'Калибровка (мм/с)',fineCalibrationSpeedMmS:'Точная калибровка (мм/с)',accelerationMmSS:'Ускорение (мм/с²)',automaticModeEnabled:'Автоматический режим',autoMeasurementDelayMs:'Задержка автозапуска (мс)',needleDetectDebounceMs:'Debounce обнаружения (мс)',needleRemovedDebounceMs:'Debounce удаления (мс)',deviationGreenPercent:'Зелёный допуск (%)',deviationRedPercent:'Красный допуск (%)',buttonDebounceMs:'Debounce кнопок (мс)',contactDebounceMs:'Debounce контакта (мс)',maxMeasurementTravelMm:'Макс. ход измерения (мм)',maxCalibrationTravelMm:'Макс. ход калибровки (мм)',maxMeasurementTimeMs:'Таймаут измерения (мс)',maxCalibrationTimeMs:'Таймаут калибровки (мс)',maxContinuousManualLeftTimeMs:'Лимит ручного хода (мс)',wifiSsid:'SSID лабораторной сети',wifiPassword:'Пароль лабораторной сети',wifiConnectTimeoutMs:'Таймаут Wi-Fi (мс)',wifiRetryIntervalMs:'Повтор Wi-Fi (мс)',fallbackApSsid:'Префикс fallback AP',fallbackApPassword:'Пароль fallback AP'};
function tab(x){dash.classList.toggle('hidden',x!='dash');settings.classList.toggle('hidden',x!='settings');document.querySelectorAll('.tabs button').forEach((b,i)=>b.classList.toggle('on',(i==0)==(x=='dash')))}
function esc(x){return String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function fmt(x,u=' мм'){return x==null?'—':Number(x).toFixed(3)+u}
async function status(){try{let s=await (await fetch('/api/status')).json();state.textContent=s.stateText;error.textContent=s.error||'';length.textContent=fmt(s.lastLengthMm);devmm.textContent='Отклонение: '+(s.deviationMm==null?'—':(s.deviationMm>=0?'+':'')+Number(s.deviationMm).toFixed(3)+' мм');devpct.textContent='Отклонение: '+(s.deviationPercent==null?'—':(s.deviationPercent>=0?'+':'')+Number(s.deviationPercent).toFixed(3)+' %');let a=Math.abs(s.deviationPercent||0);result.className='card result '+(a<=s.deviationGreenPercent?'green':a<s.deviationRedPercent?'yellow':'red');facts.innerHTML=`<b>${s.calibrated?'Откалибровано':'Не откалибровано'}</b><br>Игла: ${s.needleDetected?'обнаружена':'нет'}<br>Контакт: ${s.contactClosed?'замкнут':'открыт'}<br>Двигатель: ${s.motorMoving?'движется':'удерживает'}<br>Направление: ${s.direction}<br>Измерений: ${s.measurementCount}`;wifi.innerHTML=`<b>Wi-Fi ${esc(s.wifiMode)}</b><br>SSID: ${esc(s.ssid)}<br>IP: ${esc(s.ip)}`;}catch(e){state.textContent='Нет связи с устройством'}}
async function loadConfig(){let c=await (await fetch('/api/config')).json(),h='';for(let[g,keys]of Object.entries(groups)){h+='<fieldset><legend>'+g+'</legend>';for(let k of keys){let v=c[k]??'',bool=typeof v==='boolean';h+=`<label>${names[k]}<input name="${k}" type="${bool?'checkbox':'text'}" ${bool?(v?'checked':''):`value="${esc(v)}"`}></label>`}h+='</fieldset>'}fields.innerHTML=h}form.onsubmit=async e=>{e.preventDefault();let o={};new FormData(form).forEach((v,k)=>o[k]=v);for(let e of form.querySelectorAll('input[type=checkbox]'))o[e.name]=e.checked;let r=await fetch('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)}),j=await r.json();notice.textContent=j.message||j.error||'Готово';if(r.ok)loadConfig()};async function resetConfig(){if(!confirm('Сбросить все настройки?'))return;let j=await (await fetch('/api/config/reset',{method:'POST'})).json();notice.textContent=j.message||j.error;loadConfig()};loadConfig();status();setInterval(status,400);
</script></body></html>)HTML";
