#include <cmath>
#include <cstring>
#include <string>
#include "Pins.h"
#include "DeviceConfig.h"
#include "driver/gpio.h"
#include "esp_event.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_mac.h"
#include "esp_netif.h"
#include "esp_timer.h"
#include "esp_wifi.h"
#include "nvs.h"
#include "nvs_flash.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
static const char*TAG="Gauge";static DeviceConfig cfg;static esp_timer_handle_t timer;static volatile int64_t pos=0;static volatile bool moving=0,high=0,stopRq=0,contactRq=0;static volatile int dir=0;static bool cal=0;static int64_t calPos=0;static uint32_t count=0;static float length=NAN,dev=NAN,pct=NAN;
enum State{NEEDS_CAL,IDLE,MANUAL,MA,MF,MB,CA,CF,CB,HOLD,ERR};static volatile State st=NEEDS_CAL;static int64_t deadline,backoff,contactTime;static char error[80]={};
static float spm(){return cfg.stepsPerMmOverride>0?cfg.stepsPerMmOverride:cfg.motorStepsPerRev*cfg.microsteps*cfg.gearboxRatio/cfg.screwLeadMm;}static int64_t ms(){return esp_timer_get_time()/1000;}
static void halt(){esp_timer_stop(timer);gpio_set_level(Pins::STEP_PIN,0);moving=0;high=0;dir=0;}static void step(void*){high=!high;gpio_set_level(Pins::STEP_PIN,high);if(high)pos+=dir;}
static void IRAM_ATTR isr(void*a){int p=(int)(intptr_t)a;if(p==(int)Pins::STOP_PIN)stopRq=1;else if(dir>0){contactRq=1;esp_timer_stop(timer);moving=0;}}
static bool move(int d,float v){if(v<=0)return 0;halt();dir=d;gpio_set_level(Pins::DIR_PIN,(d>0)^cfg.directionInverted);int64_t h=(int64_t)(500000/(v*spm()));if(h<20)h=20;moving=1;return esp_timer_start_periodic(timer,h)==ESP_OK;}static bool isCal(){return st==CA||st==CF||st==CB;}
static void fail(const char*s){halt();st=ERR;strncpy(error,s,sizeof(error)-1);ESP_LOGE(TAG,"%s",s);}static void finish(){halt();if(isCal()){calPos=pos;cal=1;}else{length=cfg.calibrationLengthMm+cfg.measurementSign*(calPos-pos)/spm();dev=length-cfg.calibrationLengthMm;pct=dev/cfg.calibrationLengthMm*100;count++;}st=HOLD;}
static void begin(bool c){if(gpio_get_level(Pins::CONTACT_PIN)==0){fail("MEASUREMENT_CONTACT_ALREADY_CLOSED");return;}deadline=ms()+(c?cfg.maxCalibrationTimeMs:cfg.maxMeasurementTimeMs);move(1,c?cfg.calibrationSpeedMmS:cfg.measurementSpeedMmS);st=c?CA:MA;}
static void gpioInit(){gpio_config_t o={};o.pin_bit_mask=(1ULL<<Pins::STEP_PIN)|(1ULL<<Pins::DIR_PIN)|(1ULL<<Pins::EN_PIN);o.mode=GPIO_MODE_OUTPUT;gpio_config(&o);gpio_set_level(Pins::EN_PIN,1);gpio_config_t i={};i.pin_bit_mask=(1ULL<<Pins::LEFT_PIN)|(1ULL<<Pins::STOP_PIN)|(1ULL<<Pins::MEASURE_PIN)|(1ULL<<Pins::CONTACT_PIN)|(1ULL<<Pins::CALIBRATE_PIN)|(1ULL<<Pins::NEEDLE_PIN);i.mode=GPIO_MODE_INPUT;i.pull_up_en=GPIO_PULLUP_ENABLE;gpio_config(&i);gpio_install_isr_service(ESP_INTR_FLAG_IRAM);gpio_set_intr_type(Pins::STOP_PIN,GPIO_INTR_NEGEDGE);gpio_set_intr_type(Pins::CONTACT_PIN,GPIO_INTR_NEGEDGE);gpio_isr_handler_add(Pins::STOP_PIN,isr,(void*)(intptr_t)Pins::STOP_PIN);gpio_isr_handler_add(Pins::CONTACT_PIN,isr,(void*)(intptr_t)Pins::CONTACT_PIN);gpio_set_level(Pins::EN_PIN,0);}
static void load(){nvs_handle_t h;if(nvs_open("gauge",NVS_READWRITE,&h)==ESP_OK){size_t n=0;if(nvs_get_str(h,"ap",0,&n)==ESP_OK){std::string s(n,'\0');nvs_get_str(h,"ap",s.data(),&n);cfg.apSsidPrefix=s.c_str();}nvs_close(h);}ESP_LOGI(TAG,"[CONFIG] loaded");}
static const char page[]="<!doctype html><meta charset=utf-8><title>NeedleGauge</title><h1>Измеритель игл</h1><pre id=s>...</pre><script>setInterval(async()=>s.textContent=JSON.stringify(await(await fetch('/api/status')).json(),0,2),400)</script>";
static esp_err_t root(httpd_req_t*r){httpd_resp_set_type(r,"text/html;charset=utf-8");return httpd_resp_sendstr(r,page);}static esp_err_t stat(httpd_req_t*r){cJSON*j=cJSON_CreateObject();cJSON_AddStringToObject(j,"state",st==ERR?"ERROR":cal?"IDLE":"NEEDS_CALIBRATION");cJSON_AddBoolToObject(j,"calibrated",cal);cJSON_AddBoolToObject(j,"needleDetected",gpio_get_level(Pins::NEEDLE_PIN)==0);cJSON_AddBoolToObject(j,"contactClosed",gpio_get_level(Pins::CONTACT_PIN)==0);cJSON_AddBoolToObject(j,"motorMoving",moving);cJSON_AddStringToObject(j,"direction",dir>0?"RIGHT":dir<0?"LEFT":"STOPPED");cJSON_AddNumberToObject(j,"measurementCount",count);cJSON_AddStringToObject(j,"wifiMode","AP");cJSON_AddStringToObject(j,"ip","192.168.4.1");cJSON_AddStringToObject(j,"error",error);if(!isnan(length)){cJSON_AddNumberToObject(j,"lastLengthMm",length);cJSON_AddNumberToObject(j,"deviationMm",dev);cJSON_AddNumberToObject(j,"deviationPercent",pct);}char*s=cJSON_PrintUnformatted(j);httpd_resp_set_type(r,"application/json");httpd_resp_sendstr(r,s);free(s);cJSON_Delete(j);return ESP_OK;}
static void wifi(){uint8_t mac[6];esp_read_mac(mac,ESP_MAC_WIFI_SOFTAP);char id[33];snprintf(id,sizeof(id),"%s-%02X%02X",cfg.apSsidPrefix.c_str(),mac[4],mac[5]);wifi_init_config_t x=WIFI_INIT_CONFIG_DEFAULT();esp_wifi_init(&x);wifi_config_t w={};strncpy((char*)w.ap.ssid,id,32);strncpy((char*)w.ap.password,cfg.apPassword.c_str(),63);w.ap.ssid_len=strlen(id);w.ap.channel=1;w.ap.max_connection=4;w.ap.authmode=WIFI_AUTH_WPA2_PSK;esp_wifi_set_mode(WIFI_MODE_AP);esp_wifi_set_config(WIFI_IF_AP,&w);esp_wifi_start();ESP_LOGI(TAG,"[WIFI] AP started SSID=%s IP=192.168.4.1",id);}
static void control(void*){bool pl=1,pm=1,pc=1;for(;;){bool l=gpio_get_level(Pins::LEFT_PIN),m=gpio_get_level(Pins::MEASURE_PIN),c=gpio_get_level(Pins::CALIBRATE_PIN);if(stopRq){stopRq=0;halt();st=cal?HOLD:NEEDS_CAL;}if(contactRq){contactRq=0;if(st==MA||st==MF||st==CA||st==CF){contactTime=ms();halt();}}if(!l){if(st!=MANUAL)move(-1,cfg.manualLeftSpeedMmS);st=MANUAL;}else if(!pl&&st==MANUAL){halt();st=cal?HOLD:NEEDS_CAL;}if(!m&&pm&&st!=MANUAL){if(cal)begin(0);else strcpy(error,"Требуется калибровка");}if(!c&&pc&&st!=MANUAL)begin(1);if((st==MA||st==MF||st==CA||st==CF)&&!moving&&ms()-contactTime>=cfg.contactDebounceMs){if(gpio_get_level(Pins::CONTACT_PIN)==0){if((st==MF||st==CF)||!cfg.doubleTouchEnabled)finish();else{backoff=pos-(int64_t)(cfg.contactBackoffMm*spm());move(-1,isCal()?cfg.fineCalibrationSpeedMmS:cfg.fineMeasurementSpeedMmS);st=isCal()?CB:MB;}}else move(1,.1f);}if((st==MB||st==CB)&&pos<=backoff){halt();move(1,isCal()?cfg.fineCalibrationSpeedMmS:cfg.fineMeasurementSpeedMmS);st=isCal()?CF:MF;}if((st==MA||st==MF||st==CA||st==CF)&&ms()>deadline)fail("Контакт не обнаружен");pl=l;pm=m;pc=c;vTaskDelay(pdMS_TO_TICKS(2));}}
extern "C" void app_main(){ESP_LOGI(TAG,"[BOOT] reset=%d",esp_reset_reason());nvs_flash_init();load();gpioInit();esp_timer_create_args_t a={.callback=step,.name="step"};esp_timer_create(&a,&timer);esp_netif_init();esp_event_loop_create_default();esp_netif_create_default_wifi_ap();wifi();httpd_config_t c=HTTPD_DEFAULT_CONFIG();httpd_handle_t h;httpd_start(&h,&c);httpd_uri_t u={.uri="/",.method=HTTP_GET,.handler=root};httpd_uri_t v={.uri="/api/status",.method=HTTP_GET,.handler=stat};httpd_register_uri_handler(h,&u);httpd_register_uri_handler(h,&v);xTaskCreate(control,"control",4096,0,10,0);ESP_LOGI(TAG,"[WEB] started [MOTOR] initialized [MEASURE] ready");}
